### ISSUE TITLE
Break Screen

### ISSUE THREAD

**Issue by AmmNJ** [AmmNJ/capstone-project#10]
## Value Statement
As a **user**
I need a **break screen**
to be able to **better predict the break times and stay in my productive flow and take my breaks times seriously ** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="Bildschirmfoto 2021-03-15 um 22 07 50" src="https://user-images.githubusercontent.com/69042156/111221519-e538c600-85da-11eb-8908-deae6b2f772b.png">

## Acceptance Criteria
- [x] Break screen is shared with start screen (no dedicated page), but illustration, h1 and start button are adjusted
- [x] Start button becomes a break button with timer counting down from 5 minutes (25min option) and 10 minutes (50min option)
- [x] Break button becomes gray, but does not block the user from starting the countdown. Instead, the user receives a prompt before the countdown is started to ask, whether he is sure to continue or not
- [x] Cancelling the prompt message does not reset the break timer
- [x] Continuing the prompt message starts the countdown as usual
- [x] The break screen is only visible, if the countdown is expired (not cancelled)
- [x] The duration option stays active

## Tasks
- [x] Create feature branch
- [x] Create components incl. styled-components in storybook
- [x] Write component tests
- [x] Add component to the app
- [x] Write / adjust app logic
- [x] Add missing styles  / adjust styles from parent component if necessary

## Complexity
Medium
