### ISSUE TITLE
Add Countdown

### ISSUE THREAD

**Issue by AmmNJ** [AmmNJ/capstone-project#2]
## Value Statement
As a **user**
I need a **countdown starting from 25:00 minutes**
to be able to **apply a very basic form of the pomodoro technique to increase my productivity.** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="Bildschirmfoto 2021-03-05 um 15 25 42" src="https://user-images.githubusercontent.com/69042156/110128459-19d0a480-7dc7-11eb-9a2e-a648a744319c.png">

## Acceptance Criteria
- [x] Countdown is counting down from 25:00 minutes
- [x] Minutes and seconds are shown and always visible
- [x] Button should be able to start and stop the countdown (not pausing!) -> the stop button resets the counter to 25:00 minutes
- [x] The button icon has to indicate a "start" and "stop" icon

## Tasks
- [x] Create feature branch
- [x] Create component incl. styled-components in storybook
- [x] Write component tests
- [x] Add component to the app
- [x] Add missing styles  / adjust styles from parent component if necessary

## Complexity
High
