### ISSUE TITLE
Add 50:00 Minutes Option

### ISSUE THREAD

**Issue by AmmNJ** [AmmNJ/capstone-project#3]
## Value Statement
As a **user**
I need an option for the **countdown starting from 50:00 minutes**
to be able to **apply a flexible approach of the pomodoro technique to adapt the technique according to my workflow.** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="UserStory 2 - Countdown Option" src="https://user-images.githubusercontent.com/69042156/110964100-1d2dd800-8353-11eb-9977-bf3b61649495.png">

## Acceptance Criteria
- [x] Countdown is counting down from 50:00 minutes
- [x] Minutes and seconds are shown and always visible
- [x] Button should be able to start and stop the countdown (not pausing!) -> the stop button resets the counter to 50:00 minutes (if 50:00 is selected) and 25:00 (if 25:00 is selected)
- [x] Two additional buttons for length selection with highlighting required (disabled while countdown is active)

## Tasks
- [x] Create feature branch
- [x] Create component incl. styled-components in storybook
- [x] Write component tests
- [x] Add component to the app
- [x] Add missing styles  / adjust styles from parent component if necessary

## Complexity
Medium
