### ISSUE TITLE
Display Time According to Countdown End

### ISSUE THREAD

**Issue by AmmNJ** [AmmNJ/capstone-project#4]
## Value Statement
As a **user**
I need an **indication of the time at the end of the countdown**
to be able to **enhance my time management while being fully concentrate on the tasks ahead and thus, be more productive.** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="Display Time at End of Countdown" src="https://user-images.githubusercontent.com/69042156/110966436-87477c80-8355-11eb-8d4c-3e5e2a232b63.png">

## Acceptance Criteria
- [x] Time is visible while countdown is active (hidden while countdown is stopped or after its finished)

## Tasks
- [x] Create feature branch
- [x] Create component incl. styled-components in storybook
- [x] Write component tests
- [x] Add component to the app
- [x] Add missing styles  / adjust styles from parent component if necessary

## Complexity
medium

**Comment by AmmNJ** [comment]
## Value Statement
As a **user**
I need an **indication of the time at the end of the countdown**
to be able to **enhance my time management while fully concentrate on the tasks ahead and thus, be more productive.** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="UserStory 3 - Display Time at End of Countdown" src="https://user-images.githubusercontent.com/69042156/110254083-e2602480-7f8d-11eb-9560-f729bf8818cf.png">

## Acceptance Criteria
- [ ] Countdown is counting down from 50:00 minutes
- [ ] Minutes and seconds are shown and always visible
- [ ] Button should be able to start and stop the countdown (not pausing!) -> the stop button resets the counter to 50:00 minutes (if 50:00 is selected) and 25:00 (if 25:00 is selected)
- [ ] Two additional buttons for length selection with hightlighting required

## Tasks
- [ ] Create feature branch
- [ ] Create component incl. styled-components in storybook
- [ ] Write component tests
- [ ] Add component to the app
- [ ] Add missing styles  / adjust styles from parent component if necessary
