### ISSUE TITLE
Countdown Pausable

### ISSUE THREAD

**Issue by AmmNJ** [AmmNJ/capstone-project#5]
## Value Statement
As a **user**
I need the **possibility to pause the countdown**
to be able to **manage unexpected breaks within my productive session without having to start again from the beginning** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="Pausable Countdown" src="https://user-images.githubusercontent.com/69042156/111219049-dd2b5700-85d7-11eb-9eb3-2594c01c1daf.png">

## Acceptance Criteria

- [x] A button to pause the timer (share position with play button - new position for stop button)
- [x] While paused, end time display is not visible - on restart, time display adapts to new calculation
- [x] Pause button is not visible while countdown not previously started

## Tasks
- [x] Create feature branch
- [x] Add font `Inter` to project
- [x] Adjust all buttons according to new SVGs
- [x] Create component incl. styled-components in storybook
- [x] Add component to the app
- [x] Add missing styles  / adjust styles from parent component if necessary

## Complexity
Medium
