### ISSUE TITLE
Starting screen

### ISSUE THREAD

**Issue by AmmNJ** [AmmNJ/capstone-project#9]
## Value Statement
As a **user**
I need a dedicated **starting screen**
to be able to **focus on the countdown and not being distracted by too many clickable options** 

## Description (Text / Scribble / Wireframe / Design)
<img width="200" alt="Starting Screen" src="https://user-images.githubusercontent.com/69042156/111219840-bf122680-85d8-11eb-8042-593653e19204.png">
<img width="200" alt="Updated Countdown Screen" src="https://user-images.githubusercontent.com/69042156/111219866-c6393480-85d8-11eb-9a0a-b19a780fb6aa.png">

## Acceptance Criteria
- [x] Starting screen is starting the countdown
- [x] Play-icon button becomes only resume button after pause
- [x] Active countdown option is visible in countdown screen
- [x] Click on stop button causes redirection to start screen
- [x] Pause does not cause redirection to start screen 

## Tasks
- [x] Create feature branch
- [x] Create component incl. styled-components in storybook
- [x] Install React Router https://reactrouter.com/web/guides/quick-start
- [x] Write component tests
- [x] Add component to the app
- [x] Write / adjust app logic
- [x] Add missing styles  / adjust styles from parent component if necessary

## Complexity
Medium
